// Generated by CoffeeScript 1.6.3
(function() {
  window.lightlist = angular.module("lightlist", ["ngRoute", "ngAnimate", "LocalStorageModule"]);

  lightlist.config(function($routeProvider) {
    $routeProvider.when("/", {
      templateUrl: "partials/home.html",
      controller: "HomeController"
    });
    $routeProvider.when("/addContact", {
      templateUrl: "partials/addContact.html",
      controller: "AddContactController"
    });
    $routeProvider.when("/contact/:id", {
      templateUrl: "partials/contact.html",
      controller: "ContactController"
    });
    $routeProvider.when("/editContact/:id", {
      templateUrl: "partials/editContact.html",
      controller: "EditController"
    });
  });

  lightlist.factory("ContactListService", function(localStorageService) {
    var pub;
    pub = {};
    pub.contacts = [];
    pub.add = function(info) {
      var curLength;
      if ((info == null) || (info.name == null) || (info.phone == null)) {
        return false;
      }
      curLength = this.contacts.length;
      info.displayName = info.name;
      if (info.surname != null) {
        info.displayName += " " + info.surname;
      }
      info.id = this.contacts.length;
      this.contacts.push(info);
      this.save();
      return info.id;
    };
    pub.update = function(contact) {
      var key, oldContact, value;
      if ((contact == null) || (contact.name == null) || (contact.phone == null) || (contact.id == null)) {
        return false;
      }
      contact.displayName = contact.name;
      if (contact.surname != null) {
        contact.displayName += " " + contact.surname;
      }
      oldContact = this.get(contact.id);
      for (key in contact) {
        value = contact[key];
        oldContact[key] = value;
      }
      this.save();
      return true;
    };
    pub.get = function(id) {
      var contact, _i, _len, _ref;
      _ref = this.contacts;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        contact = _ref[_i];
        if (contact.id === parseInt(id)) {
          return contact;
        }
      }
    };
    pub.save = function() {
      localStorageService.remove("contacts");
      return localStorageService.add("contacts", this.contacts);
    };
    pub.restore = function() {
      this.contacts = localStorageService.get("contacts");
      if (this.contacts == null) {
        return this.contacts = [];
      }
    };
    pub.removeAll = function() {
      this.contacts = [];
      return this.save();
    };
    return pub;
  });

  lightlist.factory("GroupService", function(localStorageService) {
    var pub;
    pub = {};
    pub.groups = [
      {
        id: 0,
        name: "friends"
      }, {
        id: 1,
        name: "acquaintances"
      }
    ];
    pub.add = function(name) {
      if (name == null) {
        return false;
      }
      this.groups.push(name);
      return this.save();
    };
    pub.getName = function(id) {
      var group;
      group = this.getGroup(id);
      if (group == null) {
        return false;
      }
      return group.name;
    };
    pub.getGroup = function(id) {
      var group, _i, _len, _ref;
      _ref = this.groups;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        group = _ref[_i];
        if (group.id === parseInt(id)) {
          return group;
        }
      }
    };
    pub.save = function() {
      localStorageService.remove("groups");
      return localStorageService.add("groups", this.groups);
    };
    pub.restore = function() {
      this.groups = localStorageService.get("groups");
      if (this.groups == null) {
        return this.groups = [];
      }
    };
    return pub;
  });

  lightlist.controller("HomeController", function($scope, ContactListService) {
    $scope.CLS = ContactListService;
    ContactListService.restore();
  });

  lightlist.controller("ListController", function($scope, $location, ContactListService) {
    $scope.CLS = ContactListService;
    ContactListService.restore();
    if ($scope.CLS.contacts.length === 0) {
      ContactListService.add({
        name: "Ronnie",
        surname: "O'Sullivan",
        phone: "555-6000"
      });
      ContactListService.add({
        name: "Peter",
        surname: "Parker",
        phone: "555-6001"
      });
      ContactListService.add({
        name: "Tyrion",
        surname: "Lannister",
        phone: "555-6002"
      });
    }
    $scope.openContact = function(id) {
      return $location.path("/contact/" + id);
    };
  });

  lightlist.controller("AddContactController", function($scope, $location, ContactListService, GroupService) {
    $scope.GS = GroupService;
    $scope.CLS = ContactListService;
    $scope.newcontact = {};
    $scope.add = function() {
      if (ContactListService.add($scope.newcontact)) {
        return $location.path("/");
      } else {
        return alert("THIS IS UNACCEPTABLE!!");
      }
    };
  });

  lightlist.controller("ContactController", function($scope, $routeParams, ContactListService, GroupService) {
    $scope.GS = GroupService;
    ContactListService.restore();
    $scope.contact = ContactListService.get($routeParams.id);
  });

  lightlist.controller("EditController", function($scope, $routeParams, $location, ContactListService, GroupService) {
    $scope.GS = GroupService;
    ContactListService.restore();
    $scope.contact = clone(ContactListService.get($routeParams.id));
    return $scope.edit = function() {
      if (ContactListService.update($scope.contact)) {
        return $location.path("/");
      } else {
        return alert("THIS IS UNACCEPTABLE!!");
      }
    };
  });

}).call(this);
